version: "3.9"

services:
  backend:
    build:
      context: ./bck
      args:
        BACKEND_PORT_CONTAINER: ${BACKEND_PORT_CONTAINER}
    container_name: backend
    environment:
      - DOTNET_ENVIRONMENT=Development
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT_CONTAINER}"
    volumes:
      - db_data:/app/db
    restart: on-failure

  frontend:
    build:
      context: ./web
      args:
        VITE_API_URL: "http://localhost:${BACKEND_PORT_HOST}/api" # apunta al puerto host porque navegador hace el fetch
        VITE_PORT: ${FRONTEND_PORT_CONTAINER}
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT_HOST}:${FRONTEND_PORT_CONTAINER}"
    restart: on-failure

volumes:
  db_data:
