// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Core.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalEntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6d0c75c-f179-436f-b258-37b0d7718e21"),
                            AuthorName = "Lionel Messi",
                            CreatedDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional football contract with performance bonuses and image rights clauses. Includes Champions League qualification bonuses.",
                            LegalEntityName = "FC Barcelona",
                            UpdatedDate = new DateTime(2024, 2, 20, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d7f1c65e-a279-436f-b258-37b0d7718e22"),
                            AuthorName = "Cristiano Ronaldo",
                            CreatedDate = new DateTime(2024, 1, 10, 8, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-year contract with Saudi Arabian football club. Includes ambassador roles and commercial partnerships.",
                            LegalEntityName = "Al Nassr FC"
                        },
                        new
                        {
                            Id = new Guid("e8a2d76f-b379-436f-b258-37b0d7718e23"),
                            AuthorName = "Kylian Mbappé",
                            CreatedDate = new DateTime(2024, 2, 1, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Extension contract with increased salary and release clause modifications for future transfers.",
                            LegalEntityName = "Paris Saint-Germain",
                            UpdatedDate = new DateTime(2024, 2, 25, 11, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f9a3e87b-c479-436f-b258-37b0d7718e24"),
                            AuthorName = "Neymar Jr.",
                            CreatedDate = new DateTime(2024, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Five-year contract including image rights, bonuses, and performance incentives.",
                            LegalEntityName = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("a0b4f98c-d579-436f-b258-37b0d7718e25"),
                            AuthorName = "Erling Haaland",
                            CreatedDate = new DateTime(2024, 3, 5, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Contract with release clause and annual performance bonuses for league and champions cup matches.",
                            LegalEntityName = "Manchester City"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
